services:

  mysql:
    image: mysql:8.0
    container_name: hrms-mysql-compose
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - hrms_mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10


  service-registry:
    build: ./service-registry
    container_name: hrms-service-registry-compose
    restart: unless-stopped
    ports:
      - "8762:8761"


  auth-service:
    build: ./auth-service/auth-service
    container_name: hrms-auth-service-compose
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - service-registry


  employee-service:
    build: ./employee-service
    container_name: hrms-employee-service-compose
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - service-registry


  department-service:
    build: ./department-service
    container_name: hrms-department-service-compose
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrms_department_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      JWT_SECRET: hrms-project-secret-key-which-should-be-at-least-32-characters-long
    depends_on:
      - mysql
      - service-registry

  attendance-service:
    build: ./attendance-service
    container_name: hrms-attendance-service-compose
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrms_attendance_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      JWT_SECRET: hrms-project-secret-key-which-should-be-at-least-32-characters-long
    depends_on:
      - mysql
      - service-registry
      - employee-service

  gateway-service:
    build: ./gateway-service
    container_name: hrms-gateway-service-compose
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - auth-service
      - employee-service
      - department-service
      - attendance-service

volumes:
  hrms_mysql_data: